# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthexpenditure',
            name='year',
            field=models.IntegerField(),
        ),
    ]
